
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.127.0
    restart: unless-stopped
    ports:
      - "4318:4318"
      - "9464:9464"
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    command: ["--config=/etc/otelcol-contrib/config.yaml"]


  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  payment-service:
    build: ./observability/payment-service
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector

  server:
    build: ./server
    ports:
      - "9000:9000"
    depends_on:
      - prometheus
